# Generated by Django 5.0.14 on 2026-07-22 07:12

import apps.knowledgebase.models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.knowledgebase.models.kb_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'knowledge_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledgebase.knowledgefile')),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'ordering': ['knowledge_file_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='knowledge_chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
