# Generated by Django 5.0.14 on 2026-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customeruser_name_customeruser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='human_escalation_required',
            field=models.BooleanField(default=False),
        ),
    ]
